blank_issues_enabled: false
contact_links:
  - name: Support Question
    url: https://github.com/khulnasoft-lab/vul-operator/discussions/new?category_id=18526498
    about: If you have a question about Vul operator.
