{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "vul-operator.fullname" . }}
  labels: {{- include "vul-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: vul-operator
subjects:
  - kind: ServiceAccount
    name: {{ include "vul-operator.serviceAccountName" . }}
    namespace: {{ include "vul-operator.namespace" . }}
{{- end }}
