{{- if not .Values.vul.existingSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: vul-operator-vul-config
  namespace: {{ include "vul-operator.namespace" $ }}
  labels: {{- include "vul-operator.labels" $ | nindent 4 }}
data:
  {{- with .Values.vul.githubToken }}
  vul.githubToken: {{ . | b64enc | quote }}
  {{- end }}
  {{- if or (eq .Values.vul.mode "ClientServer") .Values.operator.builtInVulServer }}
  {{- with .Values.vul.serverToken }}
  vul.serverToken: {{ . | b64enc | quote }}
  {{- end }}
  {{- with .Values.vul.serverCustomHeaders }}
  vul.serverCustomHeaders: {{ . | b64enc | quote }}
  {{- end }}
  {{- end }}
  {{- if .Values.operator.builtInVulServer }}
  {{- with .Values.vul.githubToken }}
  GITHUB_TOKEN: {{ . | b64enc | quote }}
  {{- end }}
  {{- with .Values.vul.serverToken }}
  VUL_TOKEN: {{ . | b64enc | quote }}
  {{- end }}
  VUL_USERNAME: {{ .Values.vul.serverUser  | b64enc | quote }}
  VUL_PASSWORD: {{ .Values.vul.serverPassword  | b64enc | quote }}
  {{- end }}
{{- end }}